DROP TABLE IF EXISTS PAYMENTS;

CREATE TABLE PAYMENTS
(
    id       INTEGER      NOT NULL AUTO_INCREMENT,
    order_id INTEGER      NOT NULL,
    name     VARCHAR(128) NOT NULL,
    status   VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);