spring:
  application:
    name: order-service
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:order_db
    username: ${DB_USER:sa}
    password: ${DB_SECRET:password}
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: ${SHOW_SQL:false}
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: ${FORMAT_SQL:false}
  h2:
    console.enabled: true
eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'