name: eureka-service
server:
  port : 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    status-page-url: /actuator/info
    health-check-url-path: /actuator/health

  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    enable-self-preservation: false